name: Deploy Streamlit UI to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'streamlit_ui/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image to Artifact Registry
        run: |
          IMAGE=us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cloud-run-repo/streamlit-ui-demo
          docker build -t $IMAGE ./streamlit_ui
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy streamlit-ui-demo \
            --image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cloud-run-repo/streamlit-ui-demo \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars EXTRACTOR_URL=${{ secrets.EXTRACTOR_URL }},RAW_BUCKET=${{ secrets.RAW_BUCKET }}
